### PR TITLE
Fix find error message

### LINKED ISSUE #52: Update Find Command - Give more descriptive error message
Provide an error message with better wording, and more descriptive isntructions

### PR DESCRIPTION
**Pull request by Abhijay25**
Resolves #52 

Includes correct formatting and command template

now follows the format of :

Invalid command format! 
find: (description)
Parameters: find [n/NAME] [t/TAG] [d/DATE]
Example: find n/Alex

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/FindCommand.java [hunk 1]
```diff
@@ -37,8 +37,7 @@ public CommandResult execute(Model model) {
         requireNonNull(model);
         model.updateFilteredPersonList(predicate);
         int resultCount = model.getFilteredPersonList().size();
-        return new CommandResult(
-                String.format(Messages.MESSAGE_PERSONS_LISTED_OVERVIEW, resultCount));
+        return new CommandResult(String.format(Messages.MESSAGE_PERSONS_LISTED_OVERVIEW, resultCount));
```
Comment (tathan08) [inline src/main/java/seedu/address/logic/commands/FindCommand.java]: Similarly, the readability of your code can be improved by spacing out with linebreaks.
Another alternative would be to separate with the parameters, since `String.format()` does not provide much help in reading code.
```
return new CommandResult(String.format(
        Messages.MESSAGE_PERSONS_LISTED_OVERVIEW, resultCount));
```
