### PR TITLE
Find bug fix - for names and tags

### LINKED ISSUE #60: Update Find Command - Fix bug for name and tags
When given multiple names or tags, only first one is taken, therefore Alice Tan is not considered and only Alice is taken.

Current State: Searching Alice Tan returns all 'Alice' and not just 'Alice Tan'

Expected: Search for everything that is given together (i.e. search for 'Alice Tan' instead)

Multiple names / tags to search for must each be preceded by their respective delimeter

### PR DESCRIPTION
**Pull request by Abhijay25**
Resolves #60 

Find now takes only 1 parameter for name searches : 

 - find n/Alice, shows both "Alice Tan" and "Alice Lim"
 - find n/Alice Tan, only shows "Alice Tan"

Find can now take multiple tags for search:

 - find t/teamLead mandarinSpeaking, shows all team members with "teamLead" and "mandarinSpeaking" tags

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/FindCommandTest.java [hunk 1]
```diff
@@ -62,33 +60,33 @@ public void equals() {
...
         String expectedMessage = String.format(MESSAGE_PERSONS_LISTED_OVERVIEW, 0);
-        ClientContainsKeywordsPredicate predicate =
-                preparePredicate(ClientContainsKeywordsPredicate.SearchType.NAME, " ");
+        ClientContainsKeywordsPredicate predicate = preparePredicate(ClientContainsKeywordsPredicate.SearchType.NAME,
+                                        "   "); // multiple spaces
         FindCommand command = new FindCommand(predicate);
         expectedModel.updateFilteredPersonList(predicate);
         assertCommandSuccess(command, model, expectedMessage, expectedModel);
-        assertEquals(Collections.emptyList(), model.getFilteredPersonList());
+        assertTrue(model.getFilteredPersonList().isEmpty());
```
Comment (tathan08) [inline src/test/java/seedu/address/logic/commands/FindCommandTest.java]: For blank keywords, do you mean `find  ` without any parameters?
If so, will it give an error instead of an empty list, as it's an incomplete command, according to User Guide?
Should it give the same result as `list` instead, instead of an empty list, since that would be a more intuitive approach for first-time users?

Comment (Abhijay25) [reply src/test/java/seedu/address/logic/commands/FindCommandTest.java]: with the SearchType.NAME being declared, it is of the form find n/, with the parameter being missing (the second input value). It will currently throw an error, but will be changed to list all team members for a more intuitive experience

File: src/main/java/seedu/address/model/person/ClientContainsKeywordsPredicate.java [hunk 2]
```diff
@@ -31,26 +34,26 @@ public boolean test(Person person) {
...
+            return person.getName().fullName.toLowerCase().contains(combinedKeyword.toLowerCase());
 
         case TAG:
-            return person.getTags().stream()
-                    .map(tag -> tag.tagName.toLowerCase())
-                        .anyMatch(tagName ->
-                                keywords.stream()
-                                        .filter(keyword -> !keyword.trim().isEmpty())
-                                        .anyMatch(keyword -> tagName.equals(keyword.toLowerCase())));
+            return person.getTags().stream().map(tag -> tag.tagName.toLowerCase()).anyMatch(tagName -> keywords.stream()
```
[the remark this answers is not in the document]
Comment (Abhijay25) [reply src/main/java/seedu/address/model/person/ClientContainsKeywordsPredicate.java]: Resolved
